# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d42eaf3cea75f7e05066cf0c84017ab9f683f9d45c6ec3893639eb69e8c747ace26941e9eed3029cf3cd255129f93f2cc0cb40297e0385d26ea7cc0346322823

test:
  secret_key_base: af0c6a2c1f17a8a33db5f3db590232317e47e64e6204e2c197e72ee7be907551e3bce9e14a898a4825a8ff301b3c7caac548242f675d6d9a576551d49cc223e2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
